" All system-wide defaults are set in $VIMRUNTIME/debian.vim (usually just
" /usr/share/vim/vimcurrent/debian.vim) and sourced by the call to :runtime
" you can find below.  If you wish to change any of those settings, you should
" do it in this file (/etc/vim/vimrc), since debian.vim will be overwritten
" everytime an upgrade of the vim packages is performed.  It is recommended to
" make changes after sourcing debian.vim since it alters the value of the
" 'compatible' option.

" This line should not be removed as it ensures that various options are
" properly set to work with the Vim-related packages available in Debian.
runtime! debian.vim

" Uncomment the next line to make Vim more Vi-compatible
" NOTE: debian.vim sets 'nocompatible'.  Setting 'compatible' changes numerous
" options, so any other options should be set AFTER setting 'compatible'.
"set compatible
call pathogen#infect()

" Vim5 and later versions support syntax highlighting. Uncommenting the next
" line enables syntax highlighting by default.
if has("syntax")
  syntax on
endif

" If using a dark background within the editing area and syntax highlighting
" turn on this option as well
"set background=dark

" Uncomment the following to have Vim jump to the last position when
" reopening a file
"if has("autocmd")
"  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe 
"normal! g'\"" | endif
"endif
" Uncomment the following to have Vim load indentation rules and plugins
" according to the detected filetype.
if has("autocmd")
  filetype plugin indent on
endif

" The following are commented out as they cause vim to behave a lot
" differently from regular Vi. They are highly recommended though.
set showmode
set hidden
set hlsearch 
set showcmd		" Show (partial) command in status line.
set showmatch		" Show matching brackets.
set ignorecase		" Do case insensitive matching
set backspace=indent,eol,start
" set smartcase		" Do smart case matching
set incsearch		" Incremental search
set autowrite		" Automatically save before commands like :next and :make
"set hidden             " Hide buffers when they are abandoned
set mouse=a		" Enable mouse usage (all modes)
set nu
set shell=/bin/zsh
set noerrorbells
set visualbell
set t_vb=
set nowrap
set tabstop=4
set shiftwidth=4
set shiftround
set autoindent			
set foldmethod=indent
set copyindent
set gdefault

" set expandtab
nmap <F3> tabp
nmap <F4> tabnew
nnoremap <F1> za 
inoremap <F1> zf

" Source a global configuration file if available
if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif
syntax enable
set number
au WinEnter * :setlocal number
au WinLeave * :setlocal nonumber

function! Programmer() 
	set background=dark
	colorscheme solarized
"column scroll-binding on <leader>sb
	noremap <silent> <leader>sb :<C-u>let @z=&so<CR>:set so=0 noscb<CR>:bo vs<CR>Ljzt:setl scb<CR>
	<C-w>p:setl scb<CR>:let &so=@z<CR>
endfunction
function! Writer ()
	colorscheme iawriter
	set background=light
	set gfn=Cousine:h14                " font to use
	set lines=40 columns=100           " size of the editable a
	set guioptions-=r                  " remove right scrollbar
    set laststatus=0                   " don't show status line
	set noruler                        " don't show ruler
"	set fullscreen                     " go to fullscreen editing mode
	set linebreak                      " break the lines on words
endfunction
imap ( ()<Left>
imap [ []<Left>
imap { {}<Up><End>
imap /* /*<Space><Space>*/<Left><Left><Left>
" imap <  < ><Left>


